### ISSUE TITLE
figure not properly extracted 

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#24]
@gsautter Figure 1 in this document is not properly extracted and put into BLR

[140458.full.pdf](https://github.com/gsautter/goldengate-imagine/files/643810/140458.full.pdf)

![image](https://cloud.githubusercontent.com/assets/4609956/21073850/e956c950-beea-11e6-8377-52efe5a49aae.png)
![image](https://cloud.githubusercontent.com/assets/4609956/21073862/2f2675ac-beeb-11e6-80ae-99000b7c8ae5.png)

http://tb.plazi.org/GgServer/summary/FFFD9846FFBCFFEA8C58A2781854FFC6

**Comment by gsautter** [comment]
Is the figure OK in the IMF that you uploaded? Just tried to check myself, but you still hold the lock on this one ...

**Comment by myrmoteras** [comment]
no, they are not, I am still trying to understand how to annotate figCitation manually to get it to display in the text, and below in the figure tab. The former I know, the lattter I don't know yet. So, if you can fix it, that would be fine - or, again, let me know which elements are needed to get the entry right to display properly in TB.
I am released the lock now.

**Comment by gsautter** [comment]
I fixed the figure citations in this one now. However, the figure above is broken for some reason in the version on the server, while working just fine in the one I decoded from the same PDF yesterday.

Noticing that the label words are not present in the figure in the server based version, when did you decode this PDF? Could it be you decoded it before we were handling the graphics properly?

**Comment by myrmoteras** [comment]
Probably. There are many of those.  It is therefore important to have a tool to fix it.

Anyways we need to fix tools when errors are reported.  We cannot reprocessing those.


Sent from Samsung Mobile.


-------- Original message --------
From: gsautter
Date:11/12/2016 00:19 (GMT+01:00)
To: gsautter/goldengate-imagine
Cc: Donat Agosti , Author
Subject: Re: [gsautter/goldengate-imagine] figure not properly extracted (#24)


I fixed the figure citations in this one now. However, the figure above is broken for some reason in the version on the server, while working just fine in the one I decoded from the same PDF yesterday.

Noticing that the label words are not present in the figure in the server based version, when did you decode this PDF? Could it be you decoded it before we were handling the graphics properly?

-

**Comment by myrmoteras** [comment]
@gsautter the figure 1 above is till not fixed. 
https://zenodo.org/record/200194#.WE0g9lorLAQ

**Comment by gsautter** [comment]
I know it's not fixed yet, and I know we need to fix it ... because the page images proper are also a bit problematic in this one (due to the text down the right side, first and foremost), I'd best like to reuse the existing markup from the server (all the annotations you did), splice that into a freshly decoded version of the same PDF, and then upload the latter. Figure repair splices only the figures, but in this case, I'd like to also replace page images, etc. Also, the figures proper are not scrambled in this one, so figure repair won't see any need to kick into action. It's that graphics and words that are lacking, and repairing those is a bit more tricky.

I'm already in the process of figuring out a solution, just give me a day or two to complete the custom document splicing, as this has to be accurate.

**Comment by myrmoteras** [comment]
is t his a similar error in Fig. 2 here? http://tb.plazi.org/GgServer/summary/4F26FFAFFFD17F27FFCFFFD4FFC8FFD5

**Comment by gsautter** [comment]
That figure was simply not properly assigned to its caption, so the Zenodo uploader (which takes the captions and then their associated figures) could not find the figure the caption belongs to. Fixed the caption-to-figure association, and now it's there.
